[package]
name = "kasbah-groth16re"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
ark-bn254 = "0.5.0"
ark-ff = "0.5.0"
num-bigint = "0.4.6"
solana-bn254 = "2.1.13"
thiserror = "2.0.11"
